### ISSUE TITLE
Odd behaviour of the retype operator

### ISSUE THREAD

**Issue by jameseb7** [gomezabajo/Wodel#1]
I have come across some odd behaviour of the `retype` operator, which may be a bug. I have a mutation file with the following operator:
```
retypeLogicalOperator{
	retype one [And, Or] as [And, Or]
}
```
When it is applied to an XMI file containing the following:
```xmi
    <transitions name="t10" source="//@machines.0/@nodes.7" target="//@machines.0/@nodes.8">
      <condition xsi:type="robochart:Or">
        <left xsi:type="robochart:GreaterThan">
          <left xsi:type="robochart:RefExp" ref="//@machines.0/@variableList.2/@vars.0"/>
          <right xsi:type="robochart:RefExp" ref="//@machines.0/@variableList.0/@vars.0"/>
        </left>
        <right xsi:type="robochart:LessThan">
          <left xsi:type="robochart:RefExp" ref="//@machines.0/@variableList.2/@vars.0"/>
          <right xsi:type="robochart:Neg">
            <exp xsi:type="robochart:RefExp" ref="//@machines.0/@variableList.0/@vars.0"/>
          </right>
        </right>
      </condition>
    </transitions>
```
It gets changed to the following in one of the generated mutants:
```xmi
...
    <transitions name="t10" source="//@machines.0/@nodes.7" target="//@machines.0/@nodes.8">
      <condition xsi:type="robochart:Or"/>
      <probability xsi:type="robochart:And">
        <left xsi:type="robochart:GreaterThan">
          <left xsi:type="robochart:RefExp" ref="//@machines.0/@variableList.2/@vars.0"/>
          <right xsi:type="robochart:RefExp" ref="//@machines.0/@variableList.0/@vars.0"/>
        </left>
        <right xsi:type="robochart:LessThan">
          <left xsi:type="robochart:RefExp" ref="//@machines.0/@variableList.2/@vars.0"/>
          <right xsi:type="robochart:Neg">
            <exp xsi:type="robochart:RefExp" ref="//@machines.0/@variableList.0/@vars.0"/>
          </right>
        </right>
      </probability>
    </transitions>
...
```
The operator appears to change the `condition` set to`Or` into an `And`, but moves it to a separate `probability` field (which is a valid field of a transition in the metamodel, but shouldn't contain boolean expressions like `And` and `Or`). Is this expected behaviour of the `retype` operator or a bug? If it is expected behaviour, is there any way to prevent the mutated element from being moved to a sibling?

**Comment by gomezabajo** [comment]
Yes, many thanks, this is a bug in the retype operator. I've checked what you mention and there is some incompatibility with this RoboChart.ecore meta-model, or at least with these condition operators. I will try to fix it and tell you when it's ready.

**Comment by jameseb7** [comment]
Okay, thanks for looking into this!

**Comment by gomezabajo** [comment]
Dear James,

I must apologize for the delay, I've had much work to do since the last time we talked. I think now this should work, I've updated the update-site with this new Wodel version. Please, feel free to contact me again and let me know if this is working now or not. Many thanks again for your feedback, this is how software evolves :-)

Best wishes from Madrid,
Pablo
