### ISSUE TITLE
Remove all has no effect

### ISSUE THREAD

**Issue by jameseb7** [gomezabajo/Wodel#2]
I have a mutation file with the following operator block:
```
rState {
	st = select one State  
	remove all Transition where {^source = st}
	remove all Transition where {^target = st}		
	remove st     	
} 
```
The intent is that it removes a `State` and any `Transition` with a reference to that state. However, it seems the `Transition`s aren't removed. Further investigation revealed that `remove all` mutators seem to never have an effect (for any element type), although they are accepted by the mutation operator DSL. Also, `remove all` operators without a `where` clause seem to generate Java files with errors.

**Comment by gomezabajo** [comment]
This should be working now. Many thanks for your feedback, James :-) Please, let me know if this is properly working for your purposes. The other bug with the retype operator will take me a few days more. Best wishes and many thanks.

**Comment by jameseb7** [comment]
Okay, thanks for fixing this! It does appear to work correctly now for the operators I have using `remove all`. I'm glad the feedback is helpful. The operator without a `where` clause seems to work correctly as well now.
